version: '3.8'


services:
  migrate:
    image: migrate/migrate
    volumes: 
      - .:/app
    working_dir: /app
    env_file: 
      - .env
    links:
      - db
    profiles:
      - donotstart

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shoshilinch
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"